version: '3'
volumes:
  db:
    driver:
      local
services:
  nest-api:
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    links:
      - db  
    environment:
      NODE_ENV: "development"
      PORT: 3000
    ports:
      - "3000:3000"
    command: "npm run start:dev"

  db:
    image: mysql:5.6
    volumes:
      - "db:/data/db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: clock
      TZ: Asia/Dhaka
    ports:
      - 3306:3306
