version: '3'
volumes:
  db:
    driver:
      local

services:
  nest-api:
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mysql-nest-api
    links:
      - mysql-nest-api  
    environment:
      NODE_ENV: "development"
      PORT: 3000
      DB_HOST: 'mysql-nest-api'
      DB_PORT: '3306'
      DB_USERNAME: 'nest_api'
      DB_PASSWORD: 'password'
      DB_DATABASE: 'nest_api_db'
    ports:
      - "4000:3000"
    command: "npm run start:dev"

  mysql-nest-api:
    image: bitnami/mysql:8.0.23
    ports:
      - 3310:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nest_api_db
      - MYSQL_USER=nest_api
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes: 
      - "db:/var/lib/mysql"
